controller:
  admin.username: admin
  admin.password: DqJQ2RpZ3vLzSGBuVPJPW
  serviceType: NodePort
  persistence:
    enabled: true
    existingClaim: jenkins-pv-claim
    appName: nodejs-app
image:
  repository: your-dockerhub-username/nodejs-app
  tag: latest
service:
  type: ClusterIP
  port: 3000


